apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Staging overlay — 2 replicas, v1 image (ffcd15).
# Auto-sync enabled (selfHeal=true, prune=false).
namespace: gitops-staging
resources:
- ../../base
images:
- name: quay.io/redhatworkshops/welcome-php
  newTag: ffcd15
patches:
- path: replica-patch.yaml
