apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Prod overlay — 3 replicas, larger resource limits, v1 image (ffcd15).
# No automated sync — manual approval required.
namespace: gitops-prod
resources:
- ../../base
images:
- name: quay.io/redhatworkshops/welcome-php
  newTag: latest
patches:
- path: replica-patch.yaml
- path: resources-patch.yaml
