---
# App-of-apps child — Staging Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-staging
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/enzobercasio/gitops-demo-repo                   # replaced by 03-bootstrap.sh
    targetRevision: main
    path: overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
